# Generated by Django 4.1.1 on 2022-09-11 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cat_autores',
            fields=[
                ('cod_autor', models.IntegerField(primary_key=True, serialize=False)),
                ('des_autor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='cat_editorial',
            fields=[
                ('cod_editorial', models.IntegerField(primary_key=True, serialize=False)),
                ('des_editorial', models.CharField(max_length=255)),
                ('hola_editorial', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cat_editoriales',
            fields=[
                ('cod_editorial', models.IntegerField(primary_key=True, serialize=False)),
                ('des_editorial', models.CharField(max_length=255)),
                ('hola_editorial', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cat_libros',
            fields=[
                ('cod_libro', models.IntegerField(primary_key=True, serialize=False)),
                ('tit_libro', models.CharField(max_length=255)),
                ('anio', models.SmallIntegerField()),
                ('tema', models.CharField(max_length=255)),
                ('cant_plu', models.SmallIntegerField()),
                ('cant_disponible', models.SmallIntegerField()),
                ('cod_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigoAutor', to='libros.cat_autores')),
                ('cod_editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigoEditorial', to='libros.cat_editorial')),
            ],
        ),
        migrations.CreateModel(
            name='cat_libros_plu',
            fields=[
                ('plu', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('cant_disponible', models.SmallIntegerField()),
                ('cod_libro', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='codigoLibro', to='libros.cat_libros')),
            ],
        ),
    ]
