# Generated by Django 4.1.1 on 2022-09-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cat_autores',
            fields=[
                ('cod_autor', models.IntegerField(primary_key=True, serialize=False)),
                ('des_autor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='cat_editoriales',
            fields=[
                ('cod_esitorial', models.IntegerField(primary_key=True, serialize=False)),
                ('des_editorial', models.CharField(max_length=255)),
            ],
        ),
    ]
