# Generated by Django 4.1.1 on 2022-09-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cat_libros',
            fields=[
                ('cod_libro', models.IntegerField(primary_key=True, serialize=False)),
                ('tit_libro', models.CharField(max_length=255)),
                ('anio', models.SmallIntegerField()),
                ('tema', models.CharField(max_length=255)),
                ('cant_plu', models.SmallIntegerField()),
                ('cant_disponible', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cat_libros_plu',
            fields=[
                ('plu', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('cant_disponible', models.SmallIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='cat_editoriales',
            old_name='cod_esitorial',
            new_name='cod_editorial',
        ),
    ]
