# Generated by Django 4.1.1 on 2022-09-11 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cat_editoriales',
        ),
    ]
