# Generated by Django 4.1.1 on 2022-09-11 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_delete_cat_editoriales'),
    ]

    operations = [
        migrations.CreateModel(
            name='cat_editoriales',
            fields=[
                ('cod_editorial', models.IntegerField(primary_key=True, serialize=False)),
                ('des_editorial', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='cat_libros',
            name='cod_editorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigoEditorial', to='libros.cat_editoriales'),
        ),
        migrations.DeleteModel(
            name='cat_editorial',
        ),
    ]
