# Generated by Django 4.1.1 on 2022-09-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_cat_editoriales_alter_cat_libros_cod_editorial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat_autores',
            name='cod_autor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cat_editoriales',
            name='cod_editorial',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cat_libros',
            name='cod_libro',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
