# Generated by Django 4.1.1 on 2022-09-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_alter_cat_autores_cod_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat_autores',
            name='cod_autor',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cat_editoriales',
            name='cod_editorial',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cat_libros',
            name='cod_libro',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
