# Generated by Django 4.1.1 on 2022-09-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat_personas',
            old_name='dirección',
            new_name='direccion',
        ),
    ]
