# Generated by Django 4.1.1 on 2022-09-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0002_remove_mov_enc_recibos_cod_persona_and_more'),
        ('personas', '0002_rename_dirección_cat_personas_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat_personas',
            name='cod_cargo',
        ),
        migrations.RemoveField(
            model_name='cat_personas',
            name='cod_estado_per',
        ),
        migrations.DeleteModel(
            name='cat_accesos',
        ),
        migrations.DeleteModel(
            name='cat_cargos',
        ),
        migrations.DeleteModel(
            name='cat_estados_per',
        ),
        migrations.DeleteModel(
            name='cat_personas',
        ),
    ]
