# Generated by Django 4.1.1 on 2022-09-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat_personas',
            name='cod_cargo',
        ),
        migrations.RemoveField(
            model_name='cat_personas',
            name='cod_estado_per',
        ),
    ]
