# Generated by Django 4.1.1 on 2022-09-28 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_remove_cat_personas_cod_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat_personas',
            name='cod_cargo',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.RESTRICT, related_name='codigoCargo', to='personas.cat_cargos'),
        ),
    ]
