# Generated by Django 4.1.1 on 2022-09-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0007_alter_cat_personas_cod_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat_cargos',
            name='cod_cargo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
