# Generated by Django 4.1.1 on 2022-09-28 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0008_alter_cat_cargos_cod_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat_cargos',
            name='cod_cargo',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cat_personas',
            name='cod_cargo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='codigoCargo', to='personas.cat_cargos'),
        ),
    ]
