# Generated by Django 4.1.1 on 2022-09-28 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0009_alter_cat_cargos_cod_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat_personas',
            name='cod_cargo',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, related_name='codigoCargo', to='personas.cat_cargos'),
        ),
    ]
