# Generated by Django 4.1.1 on 2022-09-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0010_alter_cat_personas_cod_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat_estados_per',
            name='id',
        ),
        migrations.AlterField(
            model_name='cat_estados_per',
            name='cod_estado_per',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
