# Generated by Django 4.1.1 on 2022-09-29 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0012_cat_personas_cod_estado_per'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat_accesos',
            name='cod_persona',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, related_name='codigoPersona', to='personas.cat_personas'),
        ),
    ]
