# Generated by Django 4.1.1 on 2022-09-29 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0013_alter_cat_accesos_cod_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat_accesos',
            name='cod_persona',
        ),
    ]
